name: "helmize"
version: "0.1.1"
usage: "helm helmize -n test my-release current_charts_path"
description: "auto inject labels and annotations into exists resources"
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/bin/helmize"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
